-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid,
  activity_type character varying NOT NULL,
  description text,
  resource_type character varying,
  resource_id character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.addon_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  addon_type text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  unit_price numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  stripe_product_id text,
  stripe_price_id text,
  stripe_price_id_monthly text,
  is_recurring boolean DEFAULT false,
  billing_interval text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT addon_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_keys (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  key_hash text,
  name text,
  rate_limit integer,
  organization_id uuid,
  key_prefix text,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.billing_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  stripe_invoice_id text,
  amount numeric NOT NULL,
  currency text DEFAULT 'USD'::text,
  status text NOT NULL,
  description text,
  invoice_pdf_url text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  paystack_reference text,
  CONSTRAINT billing_history_pkey PRIMARY KEY (id),
  CONSTRAINT billing_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.checkout_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  plan_id character varying NOT NULL,
  full_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  company character varying,
  status character varying DEFAULT 'pending'::character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT checkout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_checkout_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT checkout_sessions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT checkout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  email_type text,
  template_html text NOT NULL,
  template_text text,
  variables jsonb DEFAULT '[]'::jsonb,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT email_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.field_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_field_id uuid NOT NULL UNIQUE,
  form_id uuid NOT NULL,
  total_responses integer DEFAULT 0,
  completion_rate numeric,
  most_common_value text,
  average_value numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT field_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT field_analytics_form_field_id_fkey FOREIGN KEY (form_field_id) REFERENCES public.form_fields(id),
  CONSTRAINT field_analytics_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.file_uploads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  form_response_id uuid,
  uploaded_by uuid,
  file_name text NOT NULL,
  file_type text NOT NULL,
  file_size integer NOT NULL,
  file_url text NOT NULL,
  is_virus_scanned boolean DEFAULT false,
  scan_result text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT file_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT file_uploads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT file_uploads_form_response_id_fkey FOREIGN KEY (form_response_id) REFERENCES public.form_responses(id),
  CONSTRAINT file_uploads_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.form_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_id uuid NOT NULL,
  date date NOT NULL,
  views integer DEFAULT 0,
  starts integer DEFAULT 0,
  completions integer DEFAULT 0,
  abandoned integer DEFAULT 0,
  completion_rate numeric,
  average_time_to_complete integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT form_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT form_analytics_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.form_field_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  field_id uuid NOT NULL UNIQUE,
  form_id uuid NOT NULL,
  views integer DEFAULT 0,
  interactions integer DEFAULT 0,
  validation_errors integer DEFAULT 0,
  skip_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT form_field_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT form_field_analytics_field_id_fkey FOREIGN KEY (field_id) REFERENCES public.form_fields(id),
  CONSTRAINT form_field_analytics_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.form_fields (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_id uuid NOT NULL,
  field_order integer,
  field_type text NOT NULL,
  label text NOT NULL,
  description text,
  placeholder text,
  field_key text NOT NULL,
  is_required boolean DEFAULT false,
  validation_type text,
  validation_pattern text,
  validation_message text,
  display_options jsonb DEFAULT '{}'::jsonb,
  default_value text,
  help_text text,
  conditional_logic jsonb DEFAULT '{}'::jsonb,
  advanced_settings jsonb DEFAULT '{}'::jsonb,
  field_size text DEFAULT 'full'::text,
  is_hidden boolean DEFAULT false,
  is_disabled boolean DEFAULT false,
  is_read_only boolean DEFAULT false,
  is_step_page_break boolean DEFAULT false,
  step_page_title text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  options text,
  order_index text,
  validation_rules text,
  CONSTRAINT form_fields_pkey PRIMARY KEY (id),
  CONSTRAINT form_fields_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.form_page_analytics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_id uuid NOT NULL,
  page_index integer NOT NULL,
  views integer DEFAULT 0,
  next_clicks integer DEFAULT 0,
  back_clicks integer DEFAULT 0,
  abandon_count integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT form_page_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT form_page_analytics_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.form_publish_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL,
  publish_slug character varying NOT NULL UNIQUE,
  public_url character varying,
  password character varying,
  is_published boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  published_at timestamp without time zone,
  publish_token text,
  CONSTRAINT form_publish_links_pkey PRIMARY KEY (id),
  CONSTRAINT form_publish_links_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.form_response_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL UNIQUE,
  total_responses bigint DEFAULT 0,
  completion_rate numeric DEFAULT 0.00,
  average_completion_time_seconds integer,
  views bigint DEFAULT 0,
  last_response_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT form_response_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT form_response_analytics_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.form_responses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_id uuid NOT NULL,
  workspace_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  user_id uuid,
  submitter_email text,
  submitter_name text,
  submitter_ip text,
  submitter_user_agent text,
  response_data jsonb NOT NULL,
  status text DEFAULT 'completed'::text,
  is_read boolean DEFAULT false,
  is_starred boolean DEFAULT false,
  payment_status text,
  payment_amount numeric,
  payment_currency text,
  payment_transaction_id text,
  stripe_payment_intent_id text,
  paystack_payment_reference text,
  file_urls jsonb DEFAULT '[]'::jsonb,
  location_latitude numeric,
  location_longitude numeric,
  location_country text,
  location_city text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  respondent_id uuid,
  submitted_at time without time zone DEFAULT now(),
  CONSTRAINT form_responses_pkey PRIMARY KEY (id),
  CONSTRAINT form_responses_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT form_responses_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT form_responses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT form_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT form_responses_respondent_id_fkey FOREIGN KEY (respondent_id) REFERENCES public.users(id)
);
CREATE TABLE public.form_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  category character varying,
  thumbnail_url character varying,
  form_structure jsonb NOT NULL,
  is_published boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  created_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT form_templates_pkey PRIMARY KEY (id),
  CONSTRAINT form_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.form_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_id uuid NOT NULL,
  version_number integer NOT NULL,
  form_data jsonb NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT form_versions_pkey PRIMARY KEY (id),
  CONSTRAINT form_versions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT form_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.forms (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workspace_id uuid,
  organization_id uuid NOT NULL,
  name text,
  description text,
  slug text NOT NULL,
  form_type text DEFAULT 'contact'::text,
  status text DEFAULT 'draft'::text,
  is_public boolean DEFAULT false,
  custom_domain text,
  thank_you_page_enabled boolean DEFAULT false,
  thank_you_title text DEFAULT 'Thank you!'::text,
  thank_you_message text,
  redirect_url text,
  collect_email boolean DEFAULT false,
  collect_phone boolean DEFAULT false,
  show_progress_bar boolean DEFAULT false,
  show_form_title boolean DEFAULT true,
  show_form_description boolean DEFAULT true,
  allow_multiple_responses boolean DEFAULT false,
  max_responses integer,
  limit_one_response_per_user boolean DEFAULT false,
  anonymous_responses boolean DEFAULT false,
  require_password boolean DEFAULT false,
  form_password text,
  scheduled_open_date timestamp with time zone,
  scheduled_close_date timestamp with time zone,
  is_draft boolean DEFAULT true,
  version integer DEFAULT 1,
  background_color text DEFAULT '#FFFFFF'::text,
  text_color text DEFAULT '#000000'::text,
  button_color text DEFAULT '#3B82F6'::text,
  button_text_color text DEFAULT '#FFFFFF'::text,
  font_family text DEFAULT 'system'::text,
  logo_url text,
  custom_css text,
  configuration jsonb DEFAULT '{"theme": "light", "layout": "single"}'::jsonb,
  total_responses integer DEFAULT 0,
  total_views integer DEFAULT 0,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  is_published boolean,
  branding_config text,
  settings text,
  theme_config text,
  title text,
  CONSTRAINT forms_pkey PRIMARY KEY (id),
  CONSTRAINT forms_workspace_id_fkey FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id),
  CONSTRAINT forms_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT forms_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT fk_forms_org FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.integration_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  integration_id uuid NOT NULL,
  action character varying,
  status character varying,
  request_data jsonb,
  response_data jsonb,
  error_message text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT integration_logs_pkey PRIMARY KEY (id),
  CONSTRAINT integration_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.integrations(id)
);
CREATE TABLE public.integrations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  integration_type text NOT NULL,
  name text NOT NULL,
  description text,
  is_connected boolean DEFAULT false,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  configuration jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  provider_name text,
  CONSTRAINT integrations_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT integrations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  payment_id uuid,
  invoice_number character varying NOT NULL UNIQUE,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'NGN'::character varying,
  description text,
  status character varying DEFAULT 'draft'::character varying,
  issued_date timestamp without time zone,
  due_date timestamp without time zone,
  paid_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT invoices_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  form_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  message text,
  data jsonb DEFAULT '{}'::jsonb,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT notifications_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text DEFAULT 'member'::text,
  permissions jsonb DEFAULT '[]'::jsonb,
  joined_at timestamp with time zone DEFAULT now(),
  invited_at timestamp with time zone,
  invited_by uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  logo_url text,
  banner_url text,
  website text,
  country text,
  industry text,
  company_size text,
  tax_id text,
  billing_email text,
  timezone text DEFAULT 'UTC'::text,
  language text DEFAULT 'en'::text,
  is_active boolean DEFAULT true,
  plan_type text DEFAULT 'free'::text,
  stripe_customer_id text UNIQUE,
  paystack_customer_id text UNIQUE,
  max_forms integer DEFAULT 5,
  max_responses integer DEFAULT 1000,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  owner_id uuid,
  subscription_plan character varying DEFAULT 'free'::character varying,
  subscription_status character varying DEFAULT 'active'::character varying,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.payment_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL UNIQUE,
  stripe_account_id character varying,
  stripe_connected boolean DEFAULT false,
  stripe_charges_enabled boolean DEFAULT false,
  paystack_public_key character varying,
  paystack_secret_key character varying,
  paystack_connected boolean DEFAULT false,
  paypal_client_id character varying,
  paypal_secret character varying,
  paypal_connected boolean DEFAULT false,
  flutterwave_public_key character varying,
  flutterwave_secret_key character varying,
  flutterwave_connected boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payment_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT payment_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payment_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider character varying NOT NULL,
  api_key text NOT NULL,
  public_key text,
  secret_key text,
  merchant_id text,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payment_providers_pkey PRIMARY KEY (id),
  CONSTRAINT payment_providers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  organization_id uuid,
  payment_reference character varying NOT NULL UNIQUE,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'NGN'::character varying,
  payment_provider character varying,
  status character varying DEFAULT 'pending'::character varying,
  metadata jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payment_transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  form_id uuid,
  response_id uuid,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'NGN'::character varying,
  description character varying,
  payment_provider character varying,
  payment_id character varying UNIQUE,
  status character varying DEFAULT 'pending'::character varying,
  paid_at timestamp without time zone,
  customer_email character varying,
  customer_name character varying,
  customer_phone character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT payments_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT payments_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.form_responses(id)
);
CREATE TABLE public.plan_features (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid,
  feature_key text NOT NULL,
  feature_value text NOT NULL,
  CONSTRAINT plan_features_pkey PRIMARY KEY (id),
  CONSTRAINT plan_features_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  display_name text NOT NULL,
  description text,
  price_monthly numeric NOT NULL DEFAULT 0,
  price_yearly numeric NOT NULL DEFAULT 0,
  stripe_price_id_monthly text,
  stripe_price_id_yearly text,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promo_code_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  promo_code_id uuid NOT NULL,
  user_id uuid NOT NULL,
  organization_id uuid,
  discount_amount numeric NOT NULL,
  original_amount numeric NOT NULL,
  final_amount numeric NOT NULL,
  used_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT promo_code_usage_pkey PRIMARY KEY (id),
  CONSTRAINT promo_code_usage_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.promo_codes(id),
  CONSTRAINT promo_code_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT promo_code_usage_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.promo_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code character varying NOT NULL UNIQUE,
  description text,
  discount_type character varying DEFAULT 'percentage'::character varying,
  discount_value numeric NOT NULL,
  max_uses integer DEFAULT '-1'::integer,
  current_uses integer DEFAULT 0,
  min_order_amount numeric,
  applicable_plans ARRAY,
  valid_from timestamp without time zone NOT NULL,
  valid_until timestamp without time zone NOT NULL,
  is_active boolean DEFAULT true,
  organization_id uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
  CONSTRAINT promo_codes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.referral_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  code text NOT NULL UNIQUE,
  discount_percent integer DEFAULT 20,
  commission_percent integer DEFAULT 20,
  uses_count integer DEFAULT 0,
  total_commission_earned numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid NOT NULL,
  commission_percentage numeric NOT NULL DEFAULT 10,
  discount_percentage numeric NOT NULL DEFAULT 10,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_codes_pkey PRIMARY KEY (id),
  CONSTRAINT referral_codes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT referral_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.referral_payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  total_amount numeric NOT NULL,
  payment_method text,
  payment_details jsonb,
  status text DEFAULT 'pending'::text,
  requested_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  referral_code_id uuid,
  payout_amount numeric NOT NULL,
  payout_currency text DEFAULT 'NGN'::text,
  payout_method text,
  payout_reference text,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_payouts_pkey PRIMARY KEY (id),
  CONSTRAINT referral_payouts_referral_code_id_fkey FOREIGN KEY (referral_code_id) REFERENCES public.referral_codes(id),
  CONSTRAINT referral_payouts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.referral_redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referral_code_id uuid NOT NULL,
  referred_user_id uuid NOT NULL,
  referred_organization_id uuid NOT NULL,
  commission_amount numeric NOT NULL,
  discount_applied numeric,
  referrer_payout_id uuid,
  status text DEFAULT 'completed'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT referral_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT referral_redemptions_referral_code_id_fkey FOREIGN KEY (referral_code_id) REFERENCES public.referral_codes(id),
  CONSTRAINT referral_redemptions_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES auth.users(id),
  CONSTRAINT referral_redemptions_referred_organization_id_fkey FOREIGN KEY (referred_organization_id) REFERENCES public.organizations(id),
  CONSTRAINT referral_redemptions_referrer_payout_id_fkey FOREIGN KEY (referrer_payout_id) REFERENCES public.referral_payouts(id)
);
CREATE TABLE public.response_comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  form_response_id uuid NOT NULL,
  form_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text NOT NULL,
  is_internal boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT response_comments_pkey PRIMARY KEY (id),
  CONSTRAINT response_comments_form_response_id_fkey FOREIGN KEY (form_response_id) REFERENCES public.form_responses(id),
  CONSTRAINT response_comments_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT response_comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.response_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  response_id uuid NOT NULL,
  changed_by uuid,
  changes jsonb NOT NULL,
  change_type character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT response_history_pkey PRIMARY KEY (id),
  CONSTRAINT response_history_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.form_responses(id),
  CONSTRAINT response_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.response_values (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  response_id uuid NOT NULL,
  field_id uuid NOT NULL,
  field_key character varying NOT NULL,
  value text,
  value_type character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT response_values_pkey PRIMARY KEY (id),
  CONSTRAINT response_values_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.form_responses(id),
  CONSTRAINT response_values_field_id_fkey FOREIGN KEY (field_id) REFERENCES public.form_fields(id)
);
CREATE TABLE public.security_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  ip_address character varying,
  user_agent text,
  device_name character varying,
  device_type character varying,
  is_active boolean DEFAULT true,
  last_activity timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp without time zone,
  CONSTRAINT security_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT security_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.subscription_addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  addon_type text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  stripe_payment_intent_id text,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  user_subscription_id uuid,
  stripe_line_item_id text,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  status text DEFAULT 'active'::text,
  purchased_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paystack_reference text,
  CONSTRAINT subscription_addons_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_addons_user_subscription_id_fkey FOREIGN KEY (user_subscription_id) REFERENCES public.user_subscriptions(id),
  CONSTRAINT subscription_addons_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  plan_name text NOT NULL UNIQUE,
  plan_key text NOT NULL UNIQUE,
  description text,
  price_monthly numeric,
  price_yearly numeric,
  max_forms integer,
  max_responses_per_form integer,
  max_team_members integer,
  max_webhooks integer,
  features jsonb DEFAULT '[]'::jsonb,
  stripe_product_id text,
  stripe_price_id_monthly text,
  stripe_price_id_yearly text,
  paystack_product_id text,
  is_active boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  plan_type character varying DEFAULT 'free'::character varying,
  payment_provider character varying,
  transaction_id character varying,
  amount numeric,
  currency character varying DEFAULT 'NGN'::character varying,
  status character varying DEFAULT 'pending'::character varying,
  billing_cycle character varying DEFAULT 'monthly'::character varying,
  renewal_date timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.team_invitations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  email character varying NOT NULL,
  role character varying DEFAULT 'editor'::character varying,
  token character varying NOT NULL UNIQUE,
  status character varying DEFAULT 'pending'::character varying,
  expires_at timestamp without time zone NOT NULL,
  invited_by uuid,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT team_invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT team_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  form_response_id uuid,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  status text NOT NULL DEFAULT 'pending'::text,
  payment_method text,
  transaction_reference text UNIQUE,
  stripe_payment_intent_id text UNIQUE,
  paystack_reference text UNIQUE,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  refund_amount numeric,
  refund_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT transactions_form_response_id_fkey FOREIGN KEY (form_response_id) REFERENCES public.form_responses(id)
);
CREATE TABLE public.two_factor_auth (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  method character varying DEFAULT 'totp'::character varying,
  secret_key character varying,
  backup_codes ARRAY,
  is_enabled boolean DEFAULT false,
  is_verified boolean DEFAULT false,
  verified_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT two_factor_auth_pkey PRIMARY KEY (id),
  CONSTRAINT two_factor_auth_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.usage_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  metric text NOT NULL,
  value bigint NOT NULL DEFAULT 0,
  period_start date NOT NULL,
  period_end date,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT usage_tracking_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_2fa (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  secret character varying NOT NULL,
  backup_codes ARRAY NOT NULL,
  is_enabled boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT user_2fa_pkey PRIMARY KEY (id),
  CONSTRAINT user_2fa_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  key_name character varying NOT NULL,
  api_key character varying NOT NULL UNIQUE,
  secret_key character varying,
  is_active boolean DEFAULT true,
  last_used timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT user_api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT user_api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  integration_id character varying NOT NULL,
  api_key text,
  access_token text,
  refresh_token text,
  is_connected boolean DEFAULT true,
  connected_at timestamp without time zone DEFAULT now(),
  last_used timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT user_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT user_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_organization_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'member'::text,
  invited_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_organization_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_organization_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_organization_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_organization_roles_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.user_organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  role character varying DEFAULT 'member'::character varying,
  can_delete boolean DEFAULT false,
  can_manage_team boolean DEFAULT false,
  can_manage_billing boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_organizations_pkey PRIMARY KEY (id),
  CONSTRAINT user_organizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_organizations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  bio text,
  country text DEFAULT 'TBD'::text,
  language text DEFAULT 'en'::text,
  timezone text DEFAULT 'UTC'::text,
  phone text,
  two_factor_enabled boolean DEFAULT false,
  two_factor_secret text,
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  username text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  user_agent character varying,
  ip_address inet,
  device_info jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  last_used timestamp without time zone DEFAULT now(),
  expires_at timestamp without time zone NOT NULL,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  organization_id uuid,
  plan_id uuid,
  stripe_subscription_id text,
  stripe_customer_id text,
  status text NOT NULL DEFAULT 'active'::text,
  billing_cycle text DEFAULT 'monthly'::text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  trial_ends_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  paystack_customer_code text,
  paystack_subscription_code text,
  paystack_email_token text,
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_subscriptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying,
  full_name character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  last_login timestamp without time zone,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  verified_at timestamp without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.webhook_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  webhook_id uuid NOT NULL,
  status_code integer,
  request_body jsonb,
  response_body jsonb,
  error_message text,
  attempt integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  status text,
  CONSTRAINT webhook_logs_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_logs_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES public.webhooks(id)
);
CREATE TABLE public.webhooks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  form_id uuid,
  name text NOT NULL,
  description text,
  url text NOT NULL,
  event_type text NOT NULL,
  is_active boolean DEFAULT true,
  headers jsonb DEFAULT '{}'::jsonb,
  retry_attempts integer DEFAULT 3,
  timeout_seconds integer DEFAULT 30,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  active boolean,
  delivery_count integer,
  events text,
  failure_count integer,
  user_id uuid,
  CONSTRAINT webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT webhooks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT webhooks_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.forms(id),
  CONSTRAINT webhooks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id),
  CONSTRAINT webhooks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workspaces (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  icon text,
  color text DEFAULT '#3B82F6'::text,
  is_default boolean DEFAULT false,
  is_archived boolean DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workspaces_pkey PRIMARY KEY (id),
  CONSTRAINT workspaces_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT workspaces_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);